### ISSUE TITLE
Symfony version requirement

### ISSUE THREAD

**Issue by alex88** [regularjack/frontend-bundle#16]
You should set symfony version to at least 2.5 since `Symfony\Component\Console\Question\Question` is not available in 2.4 and it's required to generate the gulpfile

**Comment by regularjack** [comment]
Thanks for reporting this. I just fixed the issue. Once I create a new tag you'll be able to get the fix by doing `composer update regularjack/frontend-bundle`. I want to get some other fixes out before creating the tag.

**Comment by alex88** [comment]
No problem, I just upgraded my project from 2.4 to 2.5 and everything went fine ;)

**Comment by xabbuh** [comment]
@regularjack The issue with that solution is that people using Symfony with the Standard Edition from 2.3 won't get the update at all. A better solution would be to only use the `Question` class when available.

**Comment by regularjack** [comment]
@xabbuh You are indeed correct. I naively assumed `symfony-standard` allowed upgrading to minor versions, e.g. it required `symfony/console` `~2.3` but it's clearly not the case.

In fact there is no reason why Symfony 2.3 projects should not be able to use `symfony/console` 2.5 because 2.5 is backwards compatible with 2.3 but since `symfony-standard` does not allow this another solution is indeed necessary.

I'm looking into the simplest way to fix this, suggestions are welcome.
